name: Valiate

on: [push, pull_request]


jobs:
  valiate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm i
      - name: Valiate schema
        run: npm run test
